const W=240,H=160, N=W*H;
const canvas=document.getElementById('world'), ctx=canvas.getContext('2d');
const mini=document.getElementById('mini'), mctx=mini.getContext('2d');
const chart=document.getElementById('chart'), cctx=chart.getContext('2d');
const $=id=>document.getElementById(id);
let terrain=new Uint8Array(N), water=new Float32Array(N), nutrients=new Float32Array(N), plants=new Float32Array(N), stone=new Uint8Array(N);
let animals=[], predators=[], day=0, paused=false, speed=2, mutation=.01, brush='plant', brushSize=5, seed=Math.random()*999999|0;
let camera={x:0,y:0,z:4}, dragging=false,last={x:0,y:0}, drawing=false, history=[], notes=[];
const presets={temperate:{rain:.58,temp:.54,plants:.22,water:.15},desert:{rain:.18,temp:.75,plants:.07,water:.04},islands:{rain:.64,temp:.62,plants:.18,water:.35},ice:{rain:.32,temp:.18,plants:.05,water:.22},chaos:{rain:.55,temp:.66,plants:.28,water:.12,mut:.04}};
let climate={rain:.55,temp:.55,season:0};
function rnd(){seed=(seed*1664525+1013904223)>>>0;return seed/4294967296}
function idx(x,y){return ((y+H)%H)*W+((x+W)%W)}
function clamp(v,a,b){return Math.max(a,Math.min(b,v))}
function noise(x,y,s){return (Math.sin((x*12.9898+y*78.233+s)*43758.5453)%1+1)%1}
function resize(){canvas.width=innerWidth-(document.querySelector('.panel.hidden')?0:document.querySelector('.panel').offsetWidth);canvas.height=innerHeight;mini.width=150;mini.height=150;chart.width=chart.clientWidth*devicePixelRatio;chart.height=chart.clientHeight*devicePixelRatio} addEventListener('resize',resize);
function newWorld(){const p=presets[$('preset').value]; seed=Math.random()*999999|0; day=0; animals=[];predators=[];history=[];notes=[]; climate={rain:p.rain,temp:p.temp,season:0}; mutation=p.mut||mutation; $('mutation').value=Math.round(mutation*1000); for(let y=0;y<H;y++)for(let x=0;x<W;x++){let i=idx(x,y), nx=x/W-.5, ny=y/H-.5; let e=0.55*noise(x*.025,y*.025,seed)+0.25*noise(x*.06,y*.06,seed+7)+0.20*(1-Math.sqrt(nx*nx+ny*ny)); terrain[i]=e*255; stone[i]=e>.73&&rnd()<.35?1:0; water[i]=e<(p.water+.15)?clamp((p.water+.15-e)*5,0,1):0; nutrients[i]=clamp(.35+rnd()*.35+(e>.4? .25:0),0,1); plants[i]=(e>.34&&water[i]<.6&&rnd()<p.plants)?rnd()*.9:0 } for(let i=0;i<70;i++)spawnAnimal(false); for(let i=0;i<14;i++)spawnAnimal(true); addNote('New world created. Baseline ecology established with terrain, water, plants, herbivores and predators.')} 
function spawnAnimal(pred=false,x=null,y=null){let tries=200;while(tries--){let ax=x??(rnd()*W|0), ay=y??(rnd()*H|0), i=idx(ax,ay); if(!stone[i]&&water[i]<.75&&(plants[i]>.05||pred)){let a={x:ax+rnd(),y:ay+rnd(),energy:pred?1.3:.9,age:0,dna:{speed:pred?.9+rnd()*.5:.55+rnd()*.45,vision:pred?9+rnd()*10:6+rnd()*8,fear:rnd(),size:.6+rnd()*.8,eff:.6+rnd()*.7}}; (pred?predators:animals).push(a);return}}}
function step(){day++; climate.season=(Math.sin(day/180)+1)/2; climate.temp=clamp(climate.temp*.998+(0.2+climate.season*.55)*.002,0,1); if(rnd()<climate.rain*.08) rainPatch(); flowWater(); growPlants(); updateAnimals(false); updateAnimals(true); if(day%20===0) sample(); if(day%90===0) observe();}
function flowWater(){for(let k=0;k<2;k++) for(let y=H-2;y>=1;y--)for(let x=1;x<W-1;x++){let i=idx(x,y); if(water[i]<.02||stone[i])continue; let best=i, bh=terrain[i]/255+water[i]; for(const [dx,dy] of [[0,1],[-1,0],[1,0],[0,-1]]){let j=idx(x+dx,y+dy), h=terrain[j]/255+water[j]+stone[j]*2; if(h<bh){bh=h;best=j}} if(best!==i){let amt=Math.min(water[i],(terrain[i]/255+water[i]-bh)*.25); water[i]-=amt; water[best]+=amt}} for(let i=0;i<N;i++){water[i]*=.9995; if(climate.temp>.7) water[i]*=.999}}
function rainPatch(){let cx=rnd()*W|0,cy=rnd()*H|0,r=8+rnd()*24; for(let y=-r;y<=r;y++)for(let x=-r;x<=r;x++){if(x*x+y*y<r*r*rnd()){let i=idx(cx+x,cy+y);water[i]=clamp(water[i]+.08*rnd(),0,1.5)}}}
function growPlants(){for(let i=0;i<N;i++){if(stone[i]||water[i]>.85){plants[i]*=.985;continue} let wet=clamp(water[i]*2.2,0,1), temp=1-Math.abs(climate.temp-.58)*1.7, n=nutrients[i]; let growth=(wet*temp*n*climate.rain)*.018; plants[i]=clamp(plants[i]+growth-plants[i]*.003,0,1); nutrients[i]=clamp(nutrients[i]-growth*.12+(.002*(1-plants[i])),0,1); if(plants[i]>.7&&rnd()<.002){let x=i%W,y=i/W|0,j=idx(x+(rnd()*7-3|0),y+(rnd()*7-3|0)); if(!stone[j]&&water[j]<.7) plants[j]=Math.max(plants[j],.12)}}}
function mutateDNA(d){let nd={...d}; for(const k in nd) if(rnd()<mutation) nd[k]*=(.85+rnd()*.3); return nd}
function updateAnimals(pred=false){let arr=pred?predators:animals, prey=pred?animals:null; for(let n=arr.length-1;n>=0;n--){let a=arr[n]; a.age++; a.energy-= pred?.006*a.dna.speed:.004*a.dna.speed; let tx=a.x+(rnd()-.5)*a.dna.vision, ty=a.y+(rnd()-.5)*a.dna.vision; if(pred&&prey.length){let best=null,bd=999; for(const p of prey){let dx=p.x-a.x,dy=p.y-a.y,d=dx*dx+dy*dy;if(d<bd&&d<a.dna.vision*a.dna.vision){bd=d;best=p}} if(best){tx=best.x;ty=best.y}} else if(!pred){let best=-1,bv=0; for(let t=0;t<12;t++){let x=(a.x+(rnd()-.5)*a.dna.vision)|0,y=(a.y+(rnd()-.5)*a.dna.vision)|0,i=idx(x,y);let v=plants[i]+water[i]*.12-stone[i]*3;if(v>bv){bv=v;best=i}} if(best>=0){tx=best%W;ty=best/W|0}} let dx=tx-a.x,dy=ty-a.y,len=Math.hypot(dx,dy)||1; a.x=(a.x+dx/len*a.dna.speed+W)%W; a.y=(a.y+dy/len*a.dna.speed+H)%H; let i=idx(a.x|0,a.y|0); if(stone[i]){a.x-=dx/len*a.dna.speed*2;a.y-=dy/len*a.dna.speed*2} if(!pred){let eat=Math.min(plants[i],.04*a.dna.size); plants[i]-=eat; nutrients[i]+=eat*.04; a.energy+=eat*a.dna.eff} else {for(let h=animals.length-1;h>=0;h--){let q=animals[h]; if(Math.abs(q.x-a.x)<1.5&&Math.abs(q.y-a.y)<1.5){animals.splice(h,1); a.energy+=.55; nutrients[i]+=0.05; break}}} if(a.energy>1.55&&arr.length<(pred?140:700)){a.energy*=.55; arr.push({...a,x:(a.x+rnd()*4-2+W)%W,y:(a.y+rnd()*4-2+H)%H,energy:a.energy,age:0,dna:mutateDNA(a.dna)})} if(a.energy<=0||a.age>(pred?1500:1100)){nutrients[i]+=.15; arr.splice(n,1)}}}
function sample(){history.push({day,plants:countPlants(),herbs:animals.length,preds:predators.length,rain:climate.rain,temp:climate.temp}); if(history.length>300)history.shift()}
function countPlants(){let c=0;for(let i=0;i<N;i++) if(plants[i]>.08)c++;return c}
function diversity(){let all=[...animals,...predators]; if(!all.length)return 0; let v=0; for(const a of all)v+=a.dna.speed+a.dna.vision*.05+a.dna.eff; return (v/all.length).toFixed(2)}
function observe(){let p=countPlants(), h=animals.length, pr=predators.length; let text=''; if(h===0&&pr>0) text='Predators have exhausted available prey. Collapse risk is extreme.'; else if(pr===0&&h>120) text='Herbivores are expanding without predation pressure. Plant biomass may decline.'; else if(p<600) text='Plant cover is sparse. Water or nutrient scarcity is constraining the food chain.'; else if(h>pr*8&&pr>0) text='Prey populations currently exceed predator pressure. A delayed predator expansion is likely.'; else if(climate.rain<.25) text='Drought conditions are reducing water availability and slowing plant recovery.'; else text='The world is in a semi-stable cycle. Energy is moving through plants, prey and predators.'; addNote('Day '+day+': '+text)}
function addNote(t){notes.unshift(t);notes=notes.slice(0,7); $('notes').innerHTML=notes.map(n=>`<div class="note">${n}</div>`).join('')}
function render(){resize(); ctx.imageSmoothingEnabled=false; let cw=canvas.width,ch=canvas.height, cell=camera.z, ox=camera.x, oy=camera.y; ctx.fillStyle='#03060a';ctx.fillRect(0,0,cw,ch); let sx=Math.max(0,Math.floor(ox/cell)-1), sy=Math.max(0,Math.floor(oy/cell)-1), ex=Math.min(W,Math.ceil((ox+cw)/cell)+1), ey=Math.min(H,Math.ceil((oy+ch)/cell)+1); for(let y=sy;y<ey;y++)for(let x=sx;x<ex;x++){let i=idx(x,y), px=x*cell-ox,py=y*cell-oy, t=terrain[i], r=30+t*.25,g=38+t*.28,b=30+t*.10; if(water[i]>.05){r=18;g=70+water[i]*55;b=110+water[i]*90} if(stone[i]){r=95;g=99;b=105} if(plants[i]>.05){r=35;g=90+plants[i]*120;b=50} ctx.fillStyle=`rgb(${r|0},${g|0},${b|0})`;ctx.fillRect(px,py,cell+1,cell+1)} for(const a of animals) dot(a.x,a.y,2.4,'#f5d06b'); for(const p of predators) dot(p.x,p.y,2.9,'#ff6675'); drawMini(); drawChart(); updateHud(); requestAnimationFrame(render)}
function dot(x,y,s,col){let cell=camera.z; ctx.fillStyle=col; ctx.beginPath(); ctx.arc(x*cell-camera.x,y*cell-camera.y,Math.max(1.2,s*cell/4),0,7);ctx.fill()}
function drawMini(){mctx.fillStyle='#04070c';mctx.fillRect(0,0,150,150); let sx=150/W,sy=150/H; for(let y=0;y<H;y+=2)for(let x=0;x<W;x+=2){let i=idx(x,y); mctx.fillStyle=water[i]>.08?'#286fb8':plants[i]>.08?'#58d26e':stone[i]?'#808793':'#465338';mctx.fillRect(x*sx,y*sy,2*sx+1,2*sy+1)} mctx.strokeStyle='#dbeaff';mctx.strokeRect(camera.x/camera.z*sx,camera.y/camera.z*sy,canvas.width/camera.z*sx,canvas.height/camera.z*sy)}
function drawChart(){let w=chart.width,h=chart.height;cctx.clearRect(0,0,w,h); if(history.length<2)return; const maxP=Math.max(...history.map(v=>v.plants),1), maxA=Math.max(...history.map(v=>v.herbs+v.preds),1); line('plants',maxP,'#58d26e'); line('herbs',maxA,'#f5d06b'); line('preds',maxA,'#ff6675'); function line(k,max,col){cctx.strokeStyle=col;cctx.lineWidth=2*devicePixelRatio;cctx.beginPath();history.forEach((v,i)=>{let x=i/(history.length-1)*w,y=h-(v[k]/max*h*.85+4); i?cctx.lineTo(x,y):cctx.moveTo(x,y)});cctx.stroke()}}
function updateHud(){$('day').textContent=day;$('plants').textContent=countPlants();$('herbs').textContent=animals.length;$('preds').textContent=predators.length;$('temp').textContent=Math.round(climate.temp*40)+'°';$('rainVal').textContent=Math.round(climate.rain*100)+'%';$('diversity').textContent=diversity();$('speedLabel').textContent=[0,.25,.5,1,2,4,8][speed]+'x';$('mutationLabel').textContent=(mutation*100).toFixed(1)+'%';$('brushSizeLabel').textContent=brushSize}
function loop(){let ticks=[0,1,1,2,4,8,16][speed]; if(!paused) for(let i=0;i<ticks;i++) step(); setTimeout(loop,60)}
function paint(cx,cy){let x=((cx+camera.x)/camera.z)|0,y=((cy+camera.y)/camera.z)|0; for(let yy=-brushSize;yy<=brushSize;yy++)for(let xx=-brushSize;xx<=brushSize;xx++){if(xx*xx+yy*yy>brushSize*brushSize)continue; let i=idx(x+xx,y+yy); if(brush==='plant')plants[i]=1; if(brush==='water')water[i]=1.2; if(brush==='stone')stone[i]=1; if(brush==='erase'){plants[i]=0;water[i]=0;stone[i]=0} if(brush==='herbivore'&&rnd()<.08)spawnAnimal(false,x+xx,y+yy); if(brush==='predator'&&rnd()<.05)spawnAnimal(true,x+xx,y+yy)}}
canvas.onpointerdown=e=>{if(e.button===1||e.shiftKey){dragging=true}else{drawing=true;paint(e.offsetX,e.offsetY)} last={x:e.clientX,y:e.clientY}}; canvas.onpointermove=e=>{if(dragging){camera.x-=e.clientX-last.x;camera.y-=e.clientY-last.y;camera.x=clamp(camera.x,0,W*camera.z-canvas.width);camera.y=clamp(camera.y,0,H*camera.z-canvas.height)} if(drawing)paint(e.offsetX,e.offsetY); last={x:e.clientX,y:e.clientY}}; canvas.onpointerup=()=>{dragging=false;drawing=false}; canvas.onwheel=e=>{e.preventDefault(); let old=camera.z; camera.z=clamp(camera.z*(e.deltaY<0?1.2:.84),2,18); camera.x=(camera.x+e.offsetX)*(camera.z/old)-e.offsetX; camera.y=(camera.y+e.offsetY)*(camera.z/old)-e.offsetY};
$('newWorld').onclick=newWorld; $('pause').onclick=()=>{paused=!paused;$('pause').textContent=paused?'Resume':'Pause'}; $('step').onclick=step; $('focus').onclick=()=>document.body.classList.toggle('focus'); $('preset').onchange=newWorld; $('brush').onchange=e=>brush=e.target.value; $('brushSize').oninput=e=>brushSize=+e.target.value; $('speed').oninput=e=>speed=+e.target.value; $('mutation').oninput=e=>mutation=+e.target.value/1000;
$('rain').onclick=()=>{climate.rain=clamp(climate.rain+.18,0,1);for(let i=0;i<18;i++)rainPatch();addNote('Manual rain event increased surface water and short-term plant growth potential.')}; $('drought').onclick=()=>{climate.rain=clamp(climate.rain-.2,0,1);addNote('Drought event: rainfall pressure reduced. Shallow ecosystems may contract.')}; $('meteor').onclick=()=>{let cx=rnd()*W|0,cy=rnd()*H|0,r=8+rnd()*18;for(let y=-r;y<=r;y++)for(let x=-r;x<=r;x++)if(x*x+y*y<r*r){let i=idx(cx+x,cy+y);plants[i]=0;water[i]*=.2;stone[i]=rnd()<.35?1:stone[i];nutrients[i]=1} addNote('Meteor impact created a disturbance zone and released nutrients.')}; $('mutate').onclick=()=>{mutation=clamp(mutation+.02,0,.12);$('mutation').value=mutation*1000;addNote('Mutation pulse applied. Future offspring will diverge faster.')};
$('save').onclick=()=>{localStorage.elab=JSON.stringify({terrain:[...terrain],water:[...water],nutrients:[...nutrients],plants:[...plants],stone:[...stone],animals,predators,day,climate,seed,history,notes});toast('World saved')}; $('load').onclick=()=>{let s=localStorage.elab;if(!s)return toast('No save found');let o=JSON.parse(s);terrain=Uint8Array.from(o.terrain);water=Float32Array.from(o.water);nutrients=Float32Array.from(o.nutrients);plants=Float32Array.from(o.plants);stone=Uint8Array.from(o.stone);animals=o.animals;predators=o.predators;day=o.day;climate=o.climate;seed=o.seed;history=o.history||[];notes=o.notes||[];addNote('Saved world restored.')}; $('shot').onclick=()=>{let a=document.createElement('a');a.download='emergence-lab-day-'+day+'.png';a.href=canvas.toDataURL();a.click()}; $('export').onclick=()=>{let blob=new Blob([JSON.stringify({day,climate,animals:animals.length,predators:predators.length,plants:countPlants(),history},null,2)],{type:'application/json'});let a=document.createElement('a');a.download='emergence-lab-export.json';a.href=URL.createObjectURL(blob);a.click()};
function toast(t){$('toast').textContent=t;$('toast').classList.add('show');setTimeout(()=>$('toast').classList.remove('show'),1200)}
addEventListener('keydown',e=>{if(e.target.tagName==='INPUT'||e.target.tagName==='SELECT')return; if(e.code==='Space'){paused=!paused;$('pause').textContent=paused?'Resume':'Pause'} if(e.key==='f'||e.key==='F')document.body.classList.toggle('focus'); if(e.key==='p'||e.key==='P')document.querySelector('.panel').classList.toggle('hidden'); if(e.key==='s'||e.key==='S')$('save').click(); if(e.key==='l'||e.key==='L')$('load').click(); if(e.key==='r'||e.key==='R')$('rain').click(); if(e.key==='m'||e.key==='M')$('meteor').click(); const map=['plant','water','stone','herbivore','predator','erase']; if('123456'.includes(e.key)){brush=map[+e.key-1];$('brush').value=brush}});
newWorld(); resize(); loop(); render();
